name: R

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up R 4.4
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4
      - name: Install devtools
        run: install.packages("devtools")
        shell: R -e {0}
      - name: install package
        run: devtools::install_local(".")
        shell: R -e {0}
      - name: test package
        run: devtools::test()
        shell: R -e {0}