name: Continuous Testing of R Package

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R 4.4
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4
      - uses: actions/checkout@v4
      - name: install package
        run:  R -e 'install.packages("devtools")'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: install package
        run:  R -e 'devtools::install_local(".")'          
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: test package
        run: R -e 'devtools::test()'